name: Selenium UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install browsers
        run: |
          choco install googlechrome --no-progress --ignore-checksums
          choco install microsoft-edge --no-progress
          choco install firefox --no-progress

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests on Chrome
        env:
          BrowserType: Chrome
        run: dotnet test --no-build --configuration Release

      - name: Run tests on Edge
        env:
          BrowserType: Edge
        run: dotnet test --no-build --configuration Release

      - name: Run tests on Firefox
        env:
          BrowserType: Firefox
        run: dotnet test --no-build --configuration Release